execution:
  run_id: cfff-v4
  profile: local
  raw_dir: raw
  work_dir: work
  cache_dir: cache
  results_dir: results
  reports_dir: reports
  sample_sheet: samples.tsv
  use_singularity: true
  container_runtime: auto
  offline: true

paths:
  data_dir: /cpfs01/projects-HDD/cfff-47998b01bebd_HDD/rj_24212030018/workflow/data
  sif_dir: /cpfs01/projects-HDD/cfff-47998b01bebd_HDD/rj_24212030018/sif
  db_dir: /cpfs01/projects-HDD/cfff-47998b01bebd_HDD/rj_24212030018/db

containers:
  mapping_file: containers.yaml
  binds:
    - /cpfs01/projects-HDD/cfff-47998b01bebd_HDD/rj_24212030018/workflow/data
    - /cpfs01/projects-HDD/cfff-47998b01bebd_HDD/rj_24212030018/sif
    - /cpfs01/projects-HDD/cfff-47998b01bebd_HDD/rj_24212030018/db

tools:
  enabled:
    virsorter: true
    genomad: true
    coverm: true
    vclust: true
    phabox2: false
  params:
    vsearch_min_len: 1500
    busco_ratio_threshold: 0.05
    coverm: "--methods count --min-read-percent-identity 95 --min-read-aligned-percent 75 --output-format dense"
  binary:
    fastp: fastp
    bowtie2: bowtie2
    megahit: megahit
    vsearch: vsearch
    virsorter: virsorter
    genomad: genomad
    checkv: checkv
    coverm: coverm
    vclust: vclust
    seqkit: seqkit

resources:
  default_threads: 8
  threads:
    fastp: 8
    bowtie2: 8
    megahit: 16
    vsearch: 4
    virsorter: 8
    genomad: 8
    checkv: 8
    coverm: 16
    vclust: 8
    project: 8
  limits:
    checkv: 1
    virsorter: 1
    busco: 1
  estimation:
    enabled: true
    fudge: 1.2
    overrides: {}

agent:
  enabled: true
  auto_apply_risk_levels: ["low"]
  retry_limit: 1

reporting:
  language: zh
  figure_language: en

database:
  bowtie2_index: /cpfs01/projects-HDD/cfff-47998b01bebd_HDD/rj_24212030018/db/bowtie2_index
  checkv: /cpfs01/projects-HDD/cfff-47998b01bebd_HDD/rj_24212030018/db/checkv
  virsorter: /cpfs01/projects-HDD/cfff-47998b01bebd_HDD/rj_24212030018/db/db
  genomad: /cpfs01/projects-HDD/cfff-47998b01bebd_HDD/rj_24212030018/db/genomad
  busco: /cpfs01/projects-HDD/cfff-47998b01bebd_HDD/rj_24212030018/db/bacteria_odb12
  phabox2: /cpfs01/projects-HDD/cfff-47998b01bebd_HDD/rj_24212030018/db/phabox_db_v2_1
  blastn: /cpfs01/projects-HDD/cfff-47998b01bebd_HDD/rj_24212030018/db/blastn_database

chat:
  max_steps: 8
